-- Autocmds are automatically loaded on the VeryLazy event.
-- Defaults that LazyVim always sets:
-- https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add personal autocmds below.
