-- Options are automatically loaded before lazy.nvim startup.
-- Defaults that LazyVim always sets:
-- https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
--
-- ShedOS keeps this minimal on purpose: prefer LazyVim's defaults and let
-- per-project settings (.editorconfig, LSP, formatter configs) win. Add
-- personal overrides below.
