"""ShedOS theme reconciler.

Reads /etc/shedos/system.toml's [theme] section + the named palette TOML
under /etc/shedos/themes/palettes/, and renders five canonical outputs
into /etc/shedos/themes/current/:

  palette.conf    Hyprland $vars  (sourced by ~/.config/hypr/*.conf)
  palette.css     CSS @define-color  (imported by waybar/walker styles)
  greeter.toml    Concrete values for shedos-greeter
  gsettings.sh    `gsettings set …` script (executed at Hyprland startup)
  wallpaper.png   Symlink → [theme].wallpaper

Re-rendered any time `shedman apply`, `shedman theme apply`, or this
module is invoked directly. The output directory is rewritten via a
`current.tmp/ → current/` rename so a half-render never serves.
"""

import shutil
import sys
from pathlib import Path

import tomlkit


DEFAULT_PALETTE = "catppuccin-mocha-blue"
DEFAULT_WALLPAPER = "/usr/share/shedos/wallpapers/dusk.png"
DEFAULT_FONT_UI = "Inter 11"
DEFAULT_FONT_MONO = "JetBrainsMono Nerd Font"


class ThemeRenderError(Exception):
    pass


def render_theme(system_doc: dict, etc_root: Path = Path("/etc")) -> Path:
    """Render the active theme. Returns the path to the live current/ dir."""
    theme = (system_doc.get("theme") if isinstance(system_doc, dict) else None) or {}
    wallpaper = theme.get("wallpaper", DEFAULT_WALLPAPER)
    palette_name = theme.get("palette", DEFAULT_PALETTE)
    font_ui = theme.get("font_ui", DEFAULT_FONT_UI)
    font_mono = theme.get("font_mono", DEFAULT_FONT_MONO)

    palette_path = etc_root / "shedos" / "themes" / "palettes" / f"{palette_name}.toml"
    if not palette_path.is_file():
        raise ThemeRenderError(
            f"palette {palette_name!r} not found at {palette_path}"
        )
    palette = tomlkit.parse(palette_path.read_text())
    colors = {k: str(v) for k, v in dict(palette.get("colors", {})).items()}
    accent = palette.get("accent", {})
    primary_token = str(accent.get("primary", "blue"))
    secondary_token = str(accent.get("secondary", "mauve"))
    primary_hex = colors.get(primary_token, "#89b4fa")
    secondary_hex = colors.get(secondary_token, "#cba6f7")

    target = etc_root / "shedos" / "themes" / "current"
    tmp = etc_root / "shedos" / "themes" / "current.tmp"
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True)

    # palette.conf — Hyprland $vars. Hyprland's color literal is
    # `rgba(<hex>aa)` where the trailing two hex digits are alpha; we
    # default to ff (opaque) and let consumer files modulate via blends.
    conf_lines = []
    for name, hex_value in colors.items():
        conf_lines.append(f"${name} = rgba({hex_value.lstrip('#')}ff)")
    conf_lines.append(f"$accent = rgba({primary_hex.lstrip('#')}ff)")
    conf_lines.append(f"$accent_secondary = rgba({secondary_hex.lstrip('#')}ff)")
    (tmp / "palette.conf").write_text("\n".join(conf_lines) + "\n")

    # palette.css — `@define-color`. Consumed via `@import` at the top
    # of waybar/walker style.css; the name space matches palette.conf.
    css_lines = ["/* Auto-generated by shedman theme apply; do not edit. */"]
    for name, hex_value in colors.items():
        css_lines.append(f"@define-color {name} {hex_value};")
    css_lines.append(f"@define-color accent {primary_hex};")
    css_lines.append(f"@define-color accent_secondary {secondary_hex};")
    (tmp / "palette.css").write_text("\n".join(css_lines) + "\n")

    # greeter.toml — concrete config for shedos-greeter. Keeps the
    # binary unaware of palette names; it just consumes hex values.
    greeter = tomlkit.document()
    greeter["wallpaper"] = str(target / "wallpaper.png")
    fonts = tomlkit.table()
    fonts["ui"] = font_ui
    fonts["mono"] = font_mono
    greeter["fonts"] = fonts
    greeter_colors = tomlkit.table()
    greeter_colors["base"] = colors.get("base", "#1e1e2e")
    greeter_colors["text"] = colors.get("text", "#cdd6f4")
    greeter_colors["accent"] = primary_hex
    greeter_colors["red"] = colors.get("red", "#f38ba8")
    greeter["colors"] = greeter_colors
    (tmp / "greeter.toml").write_text(tomlkit.dumps(greeter))

    # gsettings.sh — runs at Hyprland startup so GNOME-style apps
    # (Nautilus, Calendar, …) inherit the right GTK theme + font.
    accent_capitalized = primary_token[:1].upper() + primary_token[1:]
    gtk_theme_name = f"Catppuccin-Mocha-Standard-{accent_capitalized}-Dark"
    gsettings = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by shedman theme apply; do not edit.\n"
        f'gsettings set org.gnome.desktop.interface gtk-theme "{gtk_theme_name}"\n'
        'gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"\n'
        'gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"\n'
        'gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"\n'
        f'gsettings set org.gnome.desktop.interface font-name "{font_ui}"\n'
    )
    (tmp / "gsettings.sh").write_text(gsettings)
    (tmp / "gsettings.sh").chmod(0o755)

    # wallpaper.png — symlink to the resolved wallpaper. Consumers
    # always reference /etc/shedos/themes/current/wallpaper.png so a
    # `shedman theme set wallpaper …` flips them all at once.
    wallpaper_link = tmp / "wallpaper.png"
    if wallpaper_link.exists() or wallpaper_link.is_symlink():
        wallpaper_link.unlink()
    wallpaper_link.symlink_to(wallpaper)

    # Atomic swap. Best-effort cleanup if `target` is in a weird shape.
    if target.is_symlink() or target.is_file():
        target.unlink()
    elif target.is_dir():
        shutil.rmtree(target)
    tmp.rename(target)
    return target


def _main() -> int:
    """CLI entry: invoked by shedman apply / shedman theme apply / .install."""
    sys_toml_path = Path("/etc/shedos/system.toml")
    if not sys_toml_path.is_file():
        print(f"theme_renderer: {sys_toml_path} not found; skipping", file=sys.stderr)
        return 0
    doc = tomlkit.parse(sys_toml_path.read_text())
    try:
        rendered = render_theme(doc)
    except ThemeRenderError as e:
        print(f"theme_renderer: {e}", file=sys.stderr)
        return 1
    print(f"theme rendered to {rendered}")
    return 0


if __name__ == "__main__":
    sys.exit(_main())
