"""ShedOS theme reconciler.

Reads /etc/shedos/system.toml's [theme] section + the named palette TOML
under /etc/shedos/themes/palettes/, and renders nine canonical outputs
into /etc/shedos/themes/current/:

  palette.lua       Lua table  (dofile'd by ~/.config/hypr/hyprland.lua;
                    drives border + shadow colors)
  palette.conf      Hyprland $vars  (legacy hyprlang form; kept for user
                    configs that still source it)
  palette.css       CSS @define-color  (imported by waybar/walker styles)
  kitty-colors.conf Terminal colors  (included by ~/.config/kitty/kitty.conf)
  mako-colors.conf  Notification colors  (included by ~/.config/mako/config)
  fzf.zsh           FZF_DEFAULT_OPTS export  (sourced by the skel .zshrc)
  greeter.toml      Concrete values for shedos-greeter / prompt-ui Theme
  gsettings.sh      `gsettings set …` script (executed at Hyprland startup)
  wallpaper.png     Symlink → [theme].wallpaper

Plus one sentinel:

  .applied-at     Unix timestamp of the most recent successful swap;
                  inotify watchers (e.g. shedos-prompt-ui) trigger off
                  this file (or off MOVED_TO on `current` from the
                  parent dir) for a single stable signal per apply.

Re-rendered any time `shedman apply`, `shedman theme apply`, or this
module is invoked directly. The output directory is rewritten via a
`current.tmp/ → current/` rename so a half-render never serves; a
validation pass before the rename refuses to swap when any output is
malformed (caller's `current/` keeps the previous good theme).
"""

import argparse
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

import tomlkit
import tomlkit.exceptions as tomlkit_exc


SCHEMA_VERSION = 1

DEFAULT_PALETTE = "catppuccin-mocha-blue"
DEFAULT_WALLPAPER = "/usr/share/shedos/wallpapers/dusk.png"
DEFAULT_FONT_UI = "Inter 11"
DEFAULT_FONT_MONO = "JetBrainsMono Nerd Font"

# Strength of the gaussian blur applied to user-set wallpapers that
# lack a shipped -blurred companion. Tuned to match the look of
# dusk-blurred.png and the other shipped variants.
WALLPAPER_BLUR_KERNEL = "0x30"

HEX_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


class ThemeRenderError(Exception):
    pass


def _resolve_theme_inputs(system_doc, etc_root):
    theme = (system_doc.get("theme") if isinstance(system_doc, dict) else None) or {}
    wallpaper = theme.get("wallpaper", DEFAULT_WALLPAPER)
    palette_name = theme.get("palette", DEFAULT_PALETTE)
    font_ui = theme.get("font_ui", DEFAULT_FONT_UI)
    font_mono = theme.get("font_mono", DEFAULT_FONT_MONO)

    palette_path = etc_root / "shedos" / "themes" / "palettes" / f"{palette_name}.toml"
    if not palette_path.is_file():
        raise ThemeRenderError(
            f"palette {palette_name!r} not found at {palette_path}"
        )
    palette = tomlkit.parse(palette_path.read_text())
    colors = {k: str(v) for k, v in dict(palette.get("colors", {})).items()}
    if not colors:
        raise ThemeRenderError(f"palette {palette_name!r} has no [colors] table")
    for name, value in colors.items():
        if not HEX_COLOR_RE.match(value):
            raise ThemeRenderError(
                f"palette {palette_name!r} color {name!r}={value!r} is not #rrggbb"
            )
    accent = palette.get("accent", {})
    primary_token = str(accent.get("primary", "blue"))
    secondary_token = str(accent.get("secondary", "mauve"))
    primary_hex = colors.get(primary_token, "#89b4fa")
    secondary_hex = colors.get(secondary_token, "#cba6f7")

    return {
        "wallpaper": wallpaper,
        "palette_name": palette_name,
        "font_ui": font_ui,
        "font_mono": font_mono,
        "colors": colors,
        "primary_token": primary_token,
        "primary_hex": primary_hex,
        "secondary_hex": secondary_hex,
    }


def _write_palette_conf(tmp, ctx):
    lines = [f"# output_schema_version = {SCHEMA_VERSION}"]
    for name, hex_value in ctx["colors"].items():
        lines.append(f"${name} = rgba({hex_value.lstrip('#')}ff)")
    lines.append(f"$accent = rgba({ctx['primary_hex'].lstrip('#')}ff)")
    lines.append(f"$accent_secondary = rgba({ctx['secondary_hex'].lstrip('#')}ff)")
    (tmp / "palette.conf").write_text("\n".join(lines) + "\n")


def _write_palette_css(tmp, ctx):
    lines = [
        f"/* output_schema_version = {SCHEMA_VERSION} */",
        "/* Auto-generated by shedman theme apply; do not edit. */",
    ]
    for name, hex_value in ctx["colors"].items():
        lines.append(f"@define-color {name} {hex_value};")
    lines.append(f"@define-color accent {ctx['primary_hex']};")
    lines.append(f"@define-color accent_secondary {ctx['secondary_hex']};")
    (tmp / "palette.css").write_text("\n".join(lines) + "\n")


def _write_palette_lua(tmp, ctx):
    # Semantic keys only: hyprland.lua merges this over its Mocha
    # fallback, so every key here must stay in sync with SHEDOS_THEME.
    def rgba(hex_value, alpha):
        return f"rgba({hex_value.lstrip('#')}{alpha})"

    colors = ctx["colors"]
    lines = [
        f"-- output_schema_version = {SCHEMA_VERSION}",
        "-- Auto-generated by shedman theme apply; do not edit.",
        "-- Loaded by ~/.config/hypr/hyprland.lua into SHEDOS_THEME.",
        "return {",
        f'    active_border1  = "{rgba(ctx["primary_hex"], "ee")}",',
        f'    active_border2  = "{rgba(ctx["secondary_hex"], "ee")}",',
        f'    inactive_border = "{rgba(colors.get("surface2", "#585b70"), "aa")}",',
        f'    shadow          = "{rgba(colors.get("base", "#1e1e2e"), "ee")}",',
        "}",
    ]
    (tmp / "palette.lua").write_text("\n".join(lines) + "\n")


def _write_greeter_toml(tmp, ctx, target):
    doc = tomlkit.document()
    doc["output_schema_version"] = SCHEMA_VERSION
    # The desktop wallpaper daemon (awww) reads `wallpaper`; lock-screen
    # consumers (greeter, shedos-screensaver --mode=lock) read
    # `wallpaper_blurred` so the desktop stays sharp while the lock
    # surface is softened.
    doc["wallpaper"] = str(target / "wallpaper.png")
    doc["wallpaper_blurred"] = str(target / "wallpaper-blurred.png")
    fonts = tomlkit.table()
    fonts["ui"] = ctx["font_ui"]
    fonts["mono"] = ctx["font_mono"]
    doc["fonts"] = fonts
    colors = tomlkit.table()
    colors["base"] = ctx["colors"].get("base", "#1e1e2e")
    colors["text"] = ctx["colors"].get("text", "#cdd6f4")
    colors["accent"] = ctx["primary_hex"]
    colors["red"] = ctx["colors"].get("red", "#f38ba8")
    # Extended tokens for the shedos-power overlay (prompt-ui Theme
    # defaults cover them when an older render lacks these keys).
    colors["accent_secondary"] = ctx["secondary_hex"]
    colors["yellow"] = ctx["colors"].get("yellow", "#f9e2af")
    colors["mantle"] = ctx["colors"].get("mantle", "#181825")
    colors["surface0"] = ctx["colors"].get("surface0", "#313244")
    colors["surface2"] = ctx["colors"].get("surface2", "#585b70")
    colors["overlay1"] = ctx["colors"].get("overlay1", "#7f849c")
    doc["colors"] = colors
    (tmp / "greeter.toml").write_text(tomlkit.dumps(doc))


def _write_kitty_colors(tmp, ctx):
    c = ctx["colors"]
    accent = ctx["primary_hex"]

    def g(name, fallback):
        return c.get(name, fallback)

    lines = [
        f"# output_schema_version = {SCHEMA_VERSION}",
        "# Auto-generated by shedman theme apply; do not edit.",
        "# Included by ~/.config/kitty/kitty.conf.",
        "",
        f"foreground              {g('text', '#cdd6f4')}",
        f"background              {g('base', '#1e1e2e')}",
        f"selection_foreground    {g('base', '#1e1e2e')}",
        f"selection_background    {g('rosewater', '#f5e0dc')}",
        "",
        f"cursor                  {g('rosewater', '#f5e0dc')}",
        f"cursor_text_color       {g('base', '#1e1e2e')}",
        "",
        f"url_color               {g('rosewater', '#f5e0dc')}",
        "",
        f"active_border_color     {accent}",
        f"inactive_border_color   {g('overlay0', '#6c7086')}",
        f"bell_border_color       {g('yellow', '#f9e2af')}",
        "",
        f"active_tab_foreground   {g('crust', '#11111b')}",
        f"active_tab_background   {accent}",
        f"inactive_tab_foreground {g('text', '#cdd6f4')}",
        f"inactive_tab_background {g('mantle', '#181825')}",
        f"tab_bar_background      {g('crust', '#11111b')}",
        "",
        f"mark1_foreground {g('base', '#1e1e2e')}",
        f"mark1_background {g('lavender', '#b4befe')}",
        f"mark2_foreground {g('base', '#1e1e2e')}",
        f"mark2_background {ctx['secondary_hex']}",
        f"mark3_foreground {g('base', '#1e1e2e')}",
        f"mark3_background {g('sapphire', '#74c7ec')}",
        "",
        f"color0 {g('surface1', '#45475a')}",
        f"color8 {g('surface2', '#585b70')}",
        f"color1 {g('red', '#f38ba8')}",
        f"color9 {g('red', '#f38ba8')}",
        f"color2  {g('green', '#a6e3a1')}",
        f"color10 {g('green', '#a6e3a1')}",
        f"color3  {g('yellow', '#f9e2af')}",
        f"color11 {g('yellow', '#f9e2af')}",
        f"color4  {g('blue', '#89b4fa')}",
        f"color12 {g('blue', '#89b4fa')}",
        f"color5  {g('pink', '#f5c2e7')}",
        f"color13 {g('pink', '#f5c2e7')}",
        f"color6  {g('teal', '#94e2d5')}",
        f"color14 {g('teal', '#94e2d5')}",
        f"color7  {g('subtext1', '#bac2de')}",
        f"color15 {g('subtext0', '#a6adc8')}",
    ]
    (tmp / "kitty-colors.conf").write_text("\n".join(lines) + "\n")


def _write_mako_colors(tmp, ctx):
    c = ctx["colors"]
    accent = ctx["primary_hex"]
    lines = [
        f"# output_schema_version = {SCHEMA_VERSION}",
        "# Auto-generated by shedman theme apply; do not edit.",
        "# Included by ~/.config/mako/config as its last global line; the",
        "# urgency sections here carry the colors, the skel sections keep",
        "# the timeouts.",
        f"background-color={c.get('base', '#1e1e2e')}dd",
        f"text-color={c.get('text', '#cdd6f4')}",
        f"border-color={accent}",
        "",
        "[urgency=low]",
        f"border-color={c.get('subtext0', '#a6adc8')}",
        "",
        "[urgency=normal]",
        f"border-color={accent}",
        "",
        "[urgency=critical]",
        f"border-color={c.get('red', '#f38ba8')}",
        f"background-color={c.get('base', '#1e1e2e')}ff",
        f"text-color={c.get('red', '#f38ba8')}",
    ]
    (tmp / "mako-colors.conf").write_text("\n".join(lines) + "\n")


def _write_fzf_zsh(tmp, ctx):
    c = ctx["colors"]
    accent = ctx["primary_hex"]
    secondary = ctx["secondary_hex"]
    lines = [
        f"# output_schema_version = {SCHEMA_VERSION}",
        "# Auto-generated by shedman theme apply; do not edit.",
        "# Sourced by the skel .zshrc; sets the fzf colors from the theme.",
        'export FZF_DEFAULT_OPTS=" \\',
        f"--color=bg+:{c.get('surface0', '#313244')},bg:{c.get('base', '#1e1e2e')}"
        f",spinner:{c.get('rosewater', '#f5e0dc')},hl:{c.get('red', '#f38ba8')} \\",
        f"--color=fg:{c.get('text', '#cdd6f4')},header:{c.get('red', '#f38ba8')}"
        f",info:{secondary},pointer:{c.get('rosewater', '#f5e0dc')} \\",
        f"--color=marker:{c.get('rosewater', '#f5e0dc')},fg+:{c.get('text', '#cdd6f4')}"
        f",prompt:{accent},hl+:{c.get('red', '#f38ba8')} \\",
        "--border='rounded' --border-label='' --preview-window='border-rounded' \\",
        "--prompt=' ' --marker='\U000f0e1e ' --pointer=' ' --separator='─'\"",
    ]
    (tmp / "fzf.zsh").write_text("\n".join(lines) + "\n")


def _write_gsettings_sh(tmp, ctx):
    accent = ctx["primary_token"]
    gtk_theme_name = f"catppuccin-mocha-{accent}-standard+default"
    body = (
        "#!/usr/bin/env bash\n"
        f"# output_schema_version={SCHEMA_VERSION}\n"
        "# Auto-generated by shedman theme apply; do not edit.\n"
        f'gsettings set org.gnome.desktop.interface gtk-theme "{gtk_theme_name}"\n'
        'gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"\n'
        'gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"\n'
        'gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"\n'
        f'gsettings set org.gnome.desktop.interface font-name "{ctx["font_ui"]}"\n'
        # Point nautilus-open-any-terminal at kitty (its default is
        # gnome-terminal); guarded — the schema ships only with the extension.
        "gsettings list-schemas 2>/dev/null"
        " | grep -qx com.github.stunkymonkey.nautilus-open-any-terminal"
        " && gsettings set com.github.stunkymonkey.nautilus-open-any-terminal"
        ' terminal "kitty"\n'
        "\n"
        '# libadwaita ignores gtk-theme-name; importing the theme\'s\n'
        '# gtk-4.0 stylesheet here pulls the Catppuccin overrides into\n'
        '# libadwaita\'s style cascade so Nautilus / file-chooser /\n'
        '# every libadwaita app picks up the accent.\n'
        'mkdir -p "$HOME/.config/gtk-4.0"\n'
        f'cat > "$HOME/.config/gtk-4.0/gtk.css" <<EOF\n'
        f'@import url("file:///usr/share/themes/{gtk_theme_name}/gtk-4.0/gtk.css");\n'
        'EOF\n'
    )
    (tmp / "gsettings.sh").write_text(body)
    (tmp / "gsettings.sh").chmod(0o755)


def _resolve_blurred_companion(wallpaper):
    """Return path to a sibling -blurred file if one exists, else None."""
    p = Path(wallpaper)
    if p.stem.endswith("-blurred"):
        return p
    sibling = p.parent / f"{p.stem}-blurred{p.suffix}"
    if sibling.is_file():
        return sibling
    return None


def _write_wallpaper_link(tmp, ctx):
    """Write wallpaper.png (sharp, for awww) and wallpaper-blurred.png
    (softened, for greeter / lock screen). The sharp file is always a
    symlink to the source; the blurred companion symlinks to a shipped
    sibling when present, otherwise it's a real file generated via
    `magick … -blur`.
    """
    sharp = tmp / "wallpaper.png"
    if sharp.exists() or sharp.is_symlink():
        sharp.unlink()
    sharp.symlink_to(ctx["wallpaper"])

    blurred = tmp / "wallpaper-blurred.png"
    if blurred.exists() or blurred.is_symlink():
        blurred.unlink()

    sibling = _resolve_blurred_companion(ctx["wallpaper"])
    if sibling is not None:
        blurred.symlink_to(sibling)
        return

    # No shipped -blurred companion; generate one. The result is a
    # real file (not a symlink) so the lock screen has something to
    # render even if the source is later moved or deleted.
    try:
        subprocess.run(
            ["magick", str(ctx["wallpaper"]),
             "-blur", WALLPAPER_BLUR_KERNEL, str(blurred)],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as e:
        raise ThemeRenderError(
            f"imagemagick not installed; cannot blur {ctx['wallpaper']}: {e}"
        )
    except subprocess.CalledProcessError as e:
        raise ThemeRenderError(
            f"failed to blur {ctx['wallpaper']}: "
            f"{e.stderr.strip() or e.stdout.strip() or 'magick exited non-zero'}"
        )


def _write_applied_at(tmp):
    (tmp / ".applied-at").write_text(f"{int(time.time())}\n")


def _validate_outputs(tmp):
    """Refuse the swap if any output failed validation. Returns list of errors."""
    errors = []
    expected = [
        "palette.lua", "palette.conf", "palette.css",
        "kitty-colors.conf", "mako-colors.conf", "fzf.zsh",
        "greeter.toml", "gsettings.sh",
    ]
    for name in expected:
        path = tmp / name
        if not path.is_file():
            errors.append(f"{name} missing")
            continue
        if path.stat().st_size == 0:
            errors.append(f"{name} is empty")

    wallpaper = tmp / "wallpaper.png"
    if not wallpaper.is_symlink():
        errors.append("wallpaper.png is not a symlink")
    else:
        resolved = wallpaper.resolve()
        if not resolved.is_file():
            errors.append(f"wallpaper symlink target {resolved} is not readable")

    blurred = tmp / "wallpaper-blurred.png"
    if not blurred.is_file():
        if blurred.is_symlink():
            errors.append(
                f"wallpaper-blurred symlink target "
                f"{blurred.resolve()} is not readable"
            )
        else:
            errors.append("wallpaper-blurred.png missing")

    if (tmp / "greeter.toml").is_file():
        try:
            doc = tomlkit.parse((tmp / "greeter.toml").read_text())
            if doc.get("output_schema_version") != SCHEMA_VERSION:
                errors.append(
                    f"greeter.toml schema version != {SCHEMA_VERSION}"
                )
            for required in ("wallpaper", "fonts", "colors"):
                if required not in doc:
                    errors.append(f"greeter.toml missing [{required}]")
        except Exception as e:
            errors.append(f"greeter.toml parse failure: {e}")

    if (tmp / "palette.css").is_file():
        text = (tmp / "palette.css").read_text()
        if "@define-color" not in text:
            errors.append("palette.css has no @define-color directives")

    return errors


def render_theme(system_doc: dict, etc_root: Path = Path("/etc"),
                 dry_run: bool = False) -> Path:
    """Render the active theme. Returns the path to the live current/ dir.

    On dry_run=True, writes outputs to a temp dir and returns that path
    (caller is responsible for inspection + cleanup).
    """
    ctx = _resolve_theme_inputs(system_doc, etc_root)

    target = etc_root / "shedos" / "themes" / "current"
    tmp = etc_root / "shedos" / "themes" / "current.tmp"
    if dry_run:
        # Use a sibling dir so reldir math (greeter.toml's wallpaper path)
        # still resolves under the same parent.
        tmp = etc_root / "shedos" / "themes" / "current.dryrun"
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True)

    write_errors = []
    writers = [
        ("palette.lua", lambda: _write_palette_lua(tmp, ctx)),
        ("palette.conf", lambda: _write_palette_conf(tmp, ctx)),
        ("palette.css", lambda: _write_palette_css(tmp, ctx)),
        ("kitty-colors.conf", lambda: _write_kitty_colors(tmp, ctx)),
        ("mako-colors.conf", lambda: _write_mako_colors(tmp, ctx)),
        ("fzf.zsh", lambda: _write_fzf_zsh(tmp, ctx)),
        ("greeter.toml", lambda: _write_greeter_toml(tmp, ctx, target)),
        ("gsettings.sh", lambda: _write_gsettings_sh(tmp, ctx)),
        ("wallpaper.png", lambda: _write_wallpaper_link(tmp, ctx)),
    ]
    for name, fn in writers:
        try:
            fn()
        except Exception as e:
            write_errors.append(f"{name}: {e}")

    validate_errors = _validate_outputs(tmp)
    all_errors = write_errors + validate_errors

    if all_errors:
        msg = "; ".join(all_errors)
        if dry_run:
            shutil.rmtree(tmp, ignore_errors=True)
        else:
            shutil.rmtree(tmp, ignore_errors=True)
        raise ThemeRenderError(f"theme outputs failed validation: {msg}")

    _write_applied_at(tmp)

    if dry_run:
        return tmp

    # Swap via a sibling -old name so there is never a moment with no
    # current/ at all (consumers dereference it at arbitrary times).
    old = target.with_name(target.name + ".old")
    if old.is_dir():
        shutil.rmtree(old)
    elif old.exists() or old.is_symlink():
        old.unlink()
    if target.exists() or target.is_symlink():
        target.rename(old)
    tmp.rename(target)
    if old.is_dir():
        shutil.rmtree(old, ignore_errors=True)
    elif old.exists() or old.is_symlink():
        old.unlink()
    return target


def _check(system_toml_path: Path) -> int:
    """Validate inputs without writing any output."""
    if not system_toml_path.is_file():
        print(f"theme_renderer --check: {system_toml_path} not found",
              file=sys.stderr)
        return 1
    try:
        doc = tomlkit.parse(system_toml_path.read_text())
        _resolve_theme_inputs(doc, Path("/etc"))
    except (tomlkit_exc.TOMLKitError, ThemeRenderError) as e:
        print(f"theme_renderer --check: {e}", file=sys.stderr)
        return 1
    print("theme inputs valid.")
    return 0


def _main() -> int:
    parser = argparse.ArgumentParser(
        prog="theme_renderer",
        description="ShedOS theme reconciler.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Validate /etc/shedos/system.toml + the named palette without "
             "writing anything. Mirrors `bump-version.sh --check`.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Render to a temp dir (current.dryrun/) instead of swapping. "
             "Useful for inspecting what `shedman theme apply` would do.",
    )
    args = parser.parse_args()

    sys_toml_path = Path("/etc/shedos/system.toml")

    if args.check:
        return _check(sys_toml_path)

    if not sys_toml_path.is_file():
        print(f"theme_renderer: {sys_toml_path} not found; skipping",
              file=sys.stderr)
        return 0

    doc = tomlkit.parse(sys_toml_path.read_text())
    try:
        rendered = render_theme(doc, dry_run=args.dry_run)
    except ThemeRenderError as e:
        print(f"theme_renderer: {e}", file=sys.stderr)
        return 1

    if args.dry_run:
        print(f"dry-run rendered to {rendered}")
    else:
        print(f"theme rendered to {rendered}")
    return 0


if __name__ == "__main__":
    sys.exit(_main())
