return {
  { "mason-org/mason.nvim" },

  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "mason-org/mason.nvim" },
    opts = {
      auto_update = true,
      run_on_start = true,
      start_delay = 3000,
      ensure_installed = {
        -- LSPs
        "angular-language-server",
        "ansible-language-server",
        "asm-lsp",
        "awk-language-server",
        "azure-pipelines-language-server",
        "bash-language-server",
        "clangd",
        "cmake-language-server",
        "css-lsp",
        "css-variables-language-server",
        "cssmodules-language-server",
        "cucumber-language-server",
        "deno",
        "docker-compose-language-service",
        "docker-language-server",
        "dockerfile-language-server",
        "emmet-ls",
        "eslint-lsp",
        "gh-actions-language-server",
        "gopls",
        "gradle-language-server",
        "helm-ls",
        "html-lsp",
        "htmx-lsp",
        "jdtls",
        "jq-lsp",
        "json-lsp",
        "jsonld-lsp",
        "kotlin-language-server",
        "lua-language-server",
        "marksman",
        "neocmakelsp",
        "nextls",
        "nginx-language-server",
        "postgres-language-server",
        "pyright",
        "ruff",
        "rust-analyzer",
        "spectral-language-server",
        "sqls",
        "svelte-language-server",
        "taplo",
        "tailwindcss-language-server",
        "terraform-ls",
        "texlab",
        "typescript-language-server",
        "vtsls",
        "vue-language-server",
        "yaml-language-server",
        "zls",

        -- Linters
        "ansible-lint",
        "checkstyle",
        "cmakelint",
        "cpplint",
        "eslint_d",
        "flake8",
        "golangci-lint",
        "hadolint",
        "htmlhint",
        "jsonlint",
        "ktlint",
        "markdownlint",
        "markdownlint-cli2",
        "ruff",
        "shellcheck",
        "sqlfluff",
        "stylelint",
        "tflint",
        "yamllint",

        -- Formatters
        "asmfmt",
        "black",
        "clang-format",
        "cmakelang",
        "gofumpt",
        "goimports",
        "google-java-format",
        "htmlbeautifier",
        "isort",
        "jq",
        "json-to-struct",
        "latexindent",
        "markdown-toc",
        "nginx-config-formatter",
        "prettier",
        "prettierd",
        "shfmt",
        "stylua",
        "yamlfmt",

        -- Debuggers
        "bash-debug-adapter",
        "codelldb",
        "cpptools",
        "debugpy",
        "delve",
        "java-debug-adapter",
        "java-test",
        "js-debug-adapter",
        "kotlin-debug-adapter",

        -- Tools
        "gh",
        "gotests",
      },
    },
    config = function(_, opts)
      require("mason-tool-installer").setup(opts)
    end,
  },
}
