#!/usr/bin/env bash
# Stage the lazy-lock.json-pinned plugin set for shedos-nvim so an
# installed system never clones or compiles anything at editor start.
set -euo pipefail

runtime_src=${1:?usage: $0 <runtime-dir> <shim-config-dir> <out-dir>}
shim_src=${2:?usage: $0 <runtime-dir> <shim-config-dir> <out-dir>}
out=${3:?usage: $0 <runtime-dir> <shim-config-dir> <out-dir>}

runtime_src=$(realpath "$runtime_src")
shim_src=$(realpath "$shim_src")

# Go writes a read-only module cache under $HOME; make it deletable.
work=$(mktemp -d); trap 'chmod -R u+w "$work" 2>/dev/null; rm -rf "$work"' EXIT
# rustup config lives in the invoking user's home; keep it reachable
# after HOME moves to the throwaway dir.
export RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}" CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
export HOME="$work" XDG_CONFIG_HOME="$work/config" XDG_DATA_HOME="$work/data" \
       XDG_STATE_HOME="$work/state" XDG_CACHE_HOME="$work/cache"
# Build against the working tree, never the host's installed copy.
export SHEDOS_NVIM_RUNTIME="$runtime_src" SHEDOS_NVIM_NO_SHIPPED=1

mkdir -p "$XDG_CONFIG_HOME"
cp -a "$shim_src" "$XDG_CONFIG_HOME/nvim"
cp "$runtime_src/lazy-lock.json" "$XDG_CONFIG_HOME/nvim/lazy-lock.json"

# restore clones and pins exactly the locked commits into the throwaway
# home; the two prebuilds cover the only plugins that would otherwise
# fetch or compile on first open.
nvim --headless "+Lazy! restore" +qa
nvim --headless "+Lazy! load nvim-treesitter" "+TSUpdateSync" +qa
if [[ -f $XDG_DATA_HOME/nvim/lazy/blink.cmp/Cargo.toml ]]; then
    (cd "$XDG_DATA_HOME/nvim/lazy/blink.cmp" && cargo build --release)
fi

mkdir -p "$out/plugins"
: > "$work/specs"
for dir in "$XDG_DATA_HOME"/nvim/lazy/*/; do
    name=$(basename "$dir")
    # The lock stores names; the remote gives the owner/repo lazy keys
    # specs by, which is what binds the dir override.
    repo=$(git -C "$dir" remote get-url origin \
        | sed -E 's#^.*github\.com[:/]##; s#\.git$##')
    cp -a "$dir" "$out/plugins/$name"
    printf '  { "%s", dir = root .. "/%s" },\n' "$repo" "$name" >> "$work/specs"
done
find "$out/plugins" -name .git -prune -exec rm -rf {} +

{
    echo '-- Generated by materialize-plugins.sh; do not edit.'
    echo 'local root = "/usr/share/shedos/nvim/plugins"'
    echo 'return {'
    cat "$work/specs"
    echo '}'
} > "$out/shipped.lua"
